name: Pull Request Size Check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check_pull_request_size:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Calculate pull request size
        id: pr-size
        run: |
          # Fetch all branches from the remote repository
          git fetch --all
          # Calculate the number of lines changed in the pull request compared to the base branch (e.g., "main")
          BASE_BRANCH=$(git rev-parse origin/main)
          HEAD_COMMIT=$(git rev-parse HEAD)
          PR_SIZE=$(git diff-tree --numstat $BASE_BRANCH..$HEAD_COMMIT | awk '{ sum+=$1 } END { print sum }')
          echo "$PR_SIZE"
          echo "::set-output name=size::$PR_SIZE"

      - name: Check pull request size
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }} # Use the secret token
        run: |
          PR_SIZE="${{ steps.pr-size.outputs.size }}"
          THRESHOLD=1 # Set the threshold here (e.g., 500 lines of code changed)
          if [ "$PR_SIZE" -gt "$THRESHOLD" ]; then
            echo "Warning: Pull request size ($PR_SIZE lines) exceeds the threshold ($THRESHOLD lines)."
            echo "Please consider splitting the changes into smaller, more manageable pull requests."
            # Leave a comment using the provided token
            # For example, using "gh" CLI:
            gh pr comment ${{ github.event.number }} -b "Warning: Pull request size exceeds the threshold. Please consider splitting the changes into smaller PRs."
            # Uncomment the above line by removing the "#" to enable the comment functionality.
            # To use "gh" CLI, you'll need to have it installed and authenticated.
            # For more information, visit https://cli.github.com/manual/
            # Alternatively, you can use GitHub REST API with "curl" or other tools.
            # exit 1 # Optionally, you can exit with an error code to prevent merging.
          fi
